from typing import Union
from pydantic import BaseModel, Field
from entities.plans import Plan


class Response(BaseModel):
    """
    Represents a response from the agent.

    Attributes:
        response (str): The response text generated by the agent.
    """
    response: str


class Act(BaseModel):
    """
    Represents an action to be executed by the agent.

    Attributes:
        action (Union[Response, Plan]): The action to be performed.
            - Use `Response` when the agent wants to respond directly to the user.
            - Use `Plan` when the agent needs to utilize more tools to provide an answer.
    """
    action: Union[Response, Plan] = Field(
        description="""Ação a ser executada. Se você quiser responder ao usuário, use Response.
                    Se você precisar usar mais ferramentas para obter a resposta, use Plan."""
    )
